version: '3.8'

services:
  bancolombia-web:
    version: '3.8'

services:
  bancolombia-web:
    build: .
    container_name: bancolombia-tarjeta
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Opcional: montar logs para debugging
      - ./logs:/var/log/nginx
    networks:
      - bancolombia-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bancolombia.rule=Host(`localhost`)"
      - "traefik.http.services.bancolombia.loadbalancer.server.port=80"

networks:
  bancolombia-network:
    driver: bridge

volumes:
  logs:
    container_name: bancolombia-tarjeta
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Opcional: montar logs para debugging
      - ./logs:/var/log/nginx
    networks:
      - bancolombia-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bancolombia.rule=Host(`localhost`)"
      - "traefik.http.services.bancolombia.loadbalancer.server.port=80"

networks:
  bancolombia-network:
    driver: bridge

volumes:
  logs:
